### ISSUE TITLE
CSS Elements for Dark Mode Users

### ISSUE THREAD

**Issue by kmcleste** [wesslen/dsba6010-spring2022#1]
There are currently several pages loading the wrong css elements, making it difficult to view material for users with dark mode enabled; whether it be through their OS or browser.

The impacted pages are:

- https://dsba6010-spring2022.netlify.app/
- https://dsba6010-spring2022.netlify.app/resource/markdown/

More links will be added as they are found

**Comment by kmcleste** [comment]
![image](https://user-images.githubusercontent.com/47370125/149017918-b6d6b430-5a18-4ec3-8075-81aa5afa229a.png)

**Comment by kmcleste** [comment]
![image](https://user-images.githubusercontent.com/47370125/149018054-4b46c2b7-fc4e-4cbd-974d-4f65ace6d304.png)

**Comment by wesslen** [comment]
completed.
